#! /bin/sh
bspc monitor DP-0 -d 1 2 3 4 5 6
bspc monitor HDMI-0 -d 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color "#a89984"
bspc config normal_border_color "#282828"

bspc rule -a 'Pavucontrol' state=floating rectangle=589x384+665+384

pgrep bspwmswallow || bspwmswallow &

